### ISSUE TITLE
Jodis最新版本0.3.0使用Jedis版本2.9.0出现方法不匹配问题

### ISSUE THREAD

**Issue by xx569029747** [CodisLabs/jodis#39]
升级了版本之后出现以下异常：
`java.lang.NoSuchMethodError: redis.clients.jedis.JedisPool.<init>(Lorg/apache/commons/pool2/impl/GenericObjectPoolConfig;Ljava/lang/String;IIILjava/lang/String;ILjava/lang/String;)V
        at com.wandoulabs.jodis.RoundRobinJedisPool.resetPools(RoundRobinJedisPool.java:267)
        at com.wandoulabs.jodis.RoundRobinJedisPool.access$200(RoundRobinJedisPool.java:64)
        at com.wandoulabs.jodis.RoundRobinJedisPool$1.childEvent(RoundRobinJedisPool.java:230)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516)`

**Comment by Apache9** [comment]
看起来需要发0.4.0了。。。

**Comment by spinlock** [comment]
大师球

**Comment by Apache9** [comment]
发了0.4.0

https://oss.sonatype.org/service/local/repositories/releases/content/io/codis/jodis/jodis/0.4.0/jodis-0.4.0.pom
