### ISSUE TITLE
No content to map due to end-of-input

### ISSUE THREAD

**Issue by flyfeifei66** [CodisLabs/jodis#57]
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: [B@72f926e6; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:2839)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2781)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2011)
	at com.wandoulabs.jodis.RoundRobinJedisPool.resetPools(RoundRobinJedisPool.java:255)
	at com.wandoulabs.jodis.RoundRobinJedisPool.<init>(RoundRobinJedisPool.java:243)
	at com.wandoulabs.jodis.RoundRobinJedisPool.<init>(RoundRobinJedisPool.java:64)
	at com.wandoulabs.jodis.RoundRobinJedisPool$Builder.build(RoundRobinJedisPool.java:479)

报这个错怎么回事

**Comment by Apache9** [comment]
看起来是读到的文件是空的所以json parse失败了？

**Comment by flyfeifei66** [comment]
找到原因了，jodis支持2.X和3.X，总之用法版本没对应上，改了一通，好了。

**Comment by freeport0421** [comment]
codis3.2.2版本  jodis0.5.1,0.4.1 都试了 仍报这个错 No content to map due to end-of-input. 你是怎么解决的？
