### ISSUE TITLE
No content to map due to end-of-input

### ISSUE THREAD

**Issue by freeport0421** [CodisLabs/jodis#63]
19:21:16.987 [main] WARN io.codis.jodis.RoundRobinJedisPool - parse /jodis/codis-demo-1/proxy failed
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3079)
	at io.codis.jodis.RoundRobinJedisPool.resetPools(RoundRobinJedisPool.java:180)
	at io.codis.jodis.RoundRobinJedisPool.<init>(RoundRobinJedisPool.java:167)
	at io.codis.jodis.RoundRobinJedisPool.<init>(RoundRobinJedisPool.java:69)
	at io.codis.jodis.RoundRobinJedisPool$Builder.build(RoundRobinJedisPool.java:412)
	at com.qlc.codis.DemoCodisApplicationTests.main(DemoCodisApplicationTests.java:13)
19:21:17.256 [main] INFO io.codis.jodis.RoundRobinJedisPool - Add new proxy: 192.168.3.15:19000
19:21:17.260 [main] INFO io.codis.jodis.RoundRobinJedisPool - Add new proxy: 192.168.3.16:19000
19:21:17.260 [Curator-PathChildrenCache-0] INFO io.codis.jodis.RoundRobinJedisPool - Receive child event: type=CONNECTION_RECONNECTED, no data

求帮助这个报错怎么解决啊

**Comment by freeport0421** [comment]
问题已解决

**Comment by TuitaKing** [comment]
....能说下如何解决的吗？ @freeport0421
